### ISSUE TITLE
Stand finden bei Webseiten die keinen Stand angeben

### ISSUE THREAD

**Issue by dadosch** [corona-zahlen-landkreis/corona_landkreis_fallzahlen_scraping#3]
"wird täglich nachmittags aktualisiert"

**Comment by dadosch** [comment]
- sigmaringen
- bodenseekreis

**Comment by debugger-zz** [comment]
Jeder webserver hat einen üblicherweise einen modified timestamp (fürs caching). Ich schau mal, ob man den nehmen kann.

**Comment by dadosch** [comment]
right now, it is possible using `scrape` to use the current date. If there are higher numbers, they will be overriden.
