### ISSUE TITLE
Weitere Datenquellen

### ISSUE THREAD

**Issue by pl31** [corona-zahlen-landkreis/corona_landkreis_fallzahlen_scraping#32]
Die Berliner-Morgenpost hat eine Echtzeitkarte unter https://interaktiv.morgenpost.de/corona-virus-karte-infektionen-deutschland-weltweit/. Ganz unten auf der Seite findet sich "Weitere Informationen zur Methodik" und dort dann folgende Link-Liste.

Eventuell ist das für historische Daten der letzten Wochen eine mögliche Quelle.

> Offizielle Quellen für Deutschland
> 
> Die Fallzahlen für Deutschland spiegeln mindestens den täglich veröffentlichen Stand des Robert-Koch-Instituts (RKI) wider. Um die Karte möglichst aktuell zu halten, nutzen wir weitere Informationen.
> 
> Von folgenden Landesbehörden erhalten wir zusätzlich regelmäßig Fallzahlen oder fragen diese ab:
> 
> - Gesundheitsministerium Baden-Württemberg: https://sozialministerium.baden-wuerttemberg.de/
> - Bayerisches Landesamt für Gesundheit und Lebensmittelsicherheit (LGL): https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/
> - Berliner Senatsverwaltung für Gesundheit: https://www.berlin.de/sen/gesundheit/themen/gesundheitsschutz-und-umwelt/infektionsschutz/#Coronavirus
> - Gesundheitsministerium Brandenburg: https://msgiv.brandenburg.de/msgiv/de/start/
> - Senatsressort für Gesundheit Bremen: https://www.gesundheit.bremen.de/
> - Hamburger Behörde für Gesundheit und Verbraucherschutz: https://www.hamburg.de/bgv/
> - Hessische Ministerium für Soziales und Integration: https://soziales.hessen.de/presse/pressemitteilungen/13
> - Gesundheitsministerium Mecklenburg-Vorpommern: https://www.regierung-mv.de/Landesregierung/wm/Aktuelles--Blickpunkte/Wichtige-Informationen-zum-Corona%E2%80%93Virus
> - Niedersächsisches Ministerium für Soziales, Gesundheit und Gleichstellung: https://www.niedersachsen.de/Coronavirus
> - Gesundheitsministerium Nordrhein-Westfalen: https://www.mags.nrw/coronavirus
> - Gesundheitsministerium Rheinland-Pfalz: https://msagd.rlp.de
> - Saarländisches Gesundheitsministerium: https://www.saarland.de/SID-CB85BD5A-85D50811/corona.htm
> - Sächsischen Staatsministerium für Soziales und Gesellschaftlichen Zusammenhalt: https://www.sms.sachsen.de/coronavirus.html
> - Ministerium für Arbeit, Soziales und Integration Sachsen-Anhalt: https://ms.sachsen-anhalt.de/aktuelles/
> - Gesundheitsministerium Schleswig-Holstein: https://www.schleswig-holstein.de/DE/Landesregierung/VIII/Presse/Pressemitteilungen/pressemitteilungen_node.html
> - Gesundheitsministerium Thüringen: https://www.tmasgff.de/covid-19
>

**Comment by dadosch** [comment]
Leider ist das eine Meldekette höher, das heißt die Daten die dort auf LK-Ebene vorliegen sind älter als die vom einzelnen LK.

**Comment by jgehrcke** [comment]
@pl31 -- great links! I also tried to curate a list of relevant state-level resources: https://github.com/jgehrcke/covid-19-germany-gae#quality-data-sources-published-by-bundesl%C3%A4nder
