### ISSUE TITLE
Would you mind adding a current 'coverage' metric to the top of the README?

### ISSUE THREAD

**Issue by jgehrcke** [corona-zahlen-landkreis/corona_landkreis_fallzahlen_scraping#46]
Maybe something like (fictitious exampe)

> **120/400 LKs are covered** right now, we need your help

and then keep this updated.

**Comment by dadosch** [comment]
I've added a sum of current supported land/stadt/kreisfreihe Stadtkreise. It is hard to give a total number number, because not all have a parseable webintreface). See also the project tab for progress.

**Comment by jgehrcke** [comment]
Thank you!! :rocket:
