### ISSUE TITLE
consolidate / compare with ZEIT ONLINE's effort

### ISSUE THREAD

**Issue by jgehrcke** [corona-zahlen-landkreis/corona_landkreis_fallzahlen_scraping#47]
It looks like ZEIT ONLINE has worked pretty hard on a similar approach, given their new data set / visualization: https://github.com/jgehrcke/covid-19-germany-gae/issues/43

Would be cool to have two projects doing this. This one here would be much more transparent than ZEIT ONLINE (who probably do a good job, but still!), a better source. Don't give up! :) :rocket: 

Their current sum validates the idea (I hope): LK data is more fresh. However, right now, it's "only" ~1000 cases not yet in the Landes-Data. Does that sound about right? A lot can be learned... :)

**Comment by dadosch** [comment]
I'm actually really curious, how they collect the data. There are a few landkreise who put up images of tables (yes, you read right).

I think we need to have a more stable way to parse the websites (especially the time data easily breaks if the LK changes something.)

Also we need more contributors, even if they contribute only 1 each, or sort which LK is parsable (see project tab)
